version: "3"

services:

  php7-mysql:
    container_name: php7-database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: euromillions
    ports:
      - "3306:3306"
    volumes:
      - "./docker-entrypoint-initdb.d/draw.sql:/docker-entrypoint-initdb.d/draw.sql"

  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
networks:
  local:
    driver: bridge